#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;



function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "https://autoscriptnobita.tk/MASTER7752/1194-client.ovpn"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "========================="
	echo "Host IP : $myip"
	echo "Port    : 443/22/80"
	echo "Squid   : 8080/3128"
	echo "========================="
	echo "Script by autoscriptnobita.tk , gunakan akaun dengan bijak"
	echo "========================="
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

	clear
	echo "--------------- Selamat datang Admin Di IP: $myip ---------------"
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')


echo -e "\e[032;1mCPU model:\e[0m $cname"
echo -e "\e[032;1mNumber of cores:\e[0m $cores"
echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
echo -e "\e[032;1mSystem uptime:\e[0m $up"
echo -e "\e[032;1mScript by:\e[0m Rasta-Team.net | http://OrangKuatSabahanTerkini/"
echo "------------------------------------------------------------------------------"
echo -e "\e[032;1mCPU model:\e[0m $cname"
echo -e "\e[032;1mNumber of cores:\e[0m $cores"
echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
echo -e "\e[032;1mSystem uptime:\e[0m $up"
echo -e "AutoScriptBy OrangKuatSabaganTerkini"
echo -e "\033[38;5;214m(1)Create Account User""\e[38;5;198m          (21)Check User Banned \e[0m"
echo -e "\033[38;5;214m(2)Generate Account SSH/Vpn""\e[38;5;198m     (22)Create Acc PPTP VPN \e[0m"
echo -e "\033[38;5;214m(3)Trial ID""\e[38;5;198m                     (23)Delete Acc PPTP VPN \e[0m"
echo -e "\033[38;5;214m(4)Topup User Account""\e[38;5;198m           (24)Check Acc Detail PPTP VPN\e[0m"  
echo -e "\033[38;5;214m(5)Change Password User""\e[38;5;198m         (25)Check login PPTP VPN\e[0m" 
echo -e "\033[38;5;214m(6)Ban User""\e[38;5;198m                     (26)Check User PPTP VPN\e[0m"
echo -e "\033[38;5;214m(7)Unbanned User""\e[38;5;198m                (27)Speedtest Server\e[0m" 
echo -e "\033[38;5;214m(8)Lock User Account""\e[38;5;198m            (28)Benchmark Server\e[0m" 
echo -e "\033[38;5;214m(9)Unlock User Account""\e[38;5;198m          (29)RAM Server \e[0m"  
echo -e "\033[38;5;214m(10)Delete User Account""\e[38;5;198m         (30)Restart OpenSSH\e[0m"
echo -e "\033[38;5;214m(11)Check User Detail""\e[38;5;198m           (31)Restart Dropbear\e[0m"
echo -e "\033[38;5;214m(12)Check User IDr""\e[38;5;198m              (32)Restart OpenVPN\e[0m"
echo -e "\033[38;5;214m(13)Cek Login Dropbear""\e[38;5;198m          (33)Restart PPTP\e[0m"
echo -e "\033[38;5;214m(14)Check User Login VPS""\e[38;5;198m        (34)Restart Webmin\e[0m"
echo -e "\033[38;5;214m(15)Kill Multi Login""\e[38;5;198m            (35)Restart Squid Proxyr\e[0m"
echo -e "\033[38;5;214m(16)Check User Account""\e[38;5;198m          (36)Restart Edit Port Server\e[0m"
echo -e "\033[38;5;214m(17)Check User Expired""\e[38;5;198m          (37)Restart Set Auto Reboot\e[0m"
echo -e "\033[38;5;214m(18)Delete User Expired""\e[38;5;198m         (38)Reboot Server\e[0m"
echo -e "\033[38;5;214m(19)Lock user expired""\e[38;5;198m           (39)Change Password Server\e[0m" 
echo -e "\033[38;5;214m(20)Check User Kicked""\e[38;5;198m           (40)Lihat Info Script\e[0m"          
echo -e "\e[38;5;198m                                                (41)Update Now\e[0m" 
	echo ""
	echo "Update Premium Script"
	echo -e "\e[031;1m38\e[0m) Update Now (\e[34;1mupdate\e[0m)"
	echo ""
	echo -e "\e[031;1m x\e[0m) Exit"
	read -p "Masukkan pilihan anda, kemudian tekan tombol ENTER: " option1
	case $option1 in
        1)  
            clear
            buatakun
            ;;
        2)  
            clear
            generate
            ;;
        3)	
            clear
            trial
			;;	
        4)
            clear
            userpass
            ;;
        5)
            clear
            userrenew
			;;
        6)
            userdelete
            ;;		
		7)
		    clear
	        userlogin
			;;
		8)
		    clear
			autolimit
			;;	
		9)
		    clear
            userdetail
            ;;
		10)
		    clear
            user-list
            ;;
        11)
               clear
               deleteuserexpire
	          ;;
	    12)
	          clear
	          #!/bin/bash
              # Created by autoscriptnobita.tk
              
              red='\e[1;31m'
              green='\e[0;32m'
              NC='\e[0m'             
              echo -e "${green}Permission Accepted...${NC}"
              sleep 0
               echo""
	           echo "    AUTO KILL MULTI LOGIN    "    
	           echo "-----------------------------"
               autokilluser
               echo "-----------------------------"
               echo "AUTO KILL MULTI LOGIN SELESAI"
               ;;
        13)
               clear
               userban
	          ;;
	    14)
               clear
               userunban
	          ;;
	    15)
	        clear
            userlock
			;;
		16)
		    clear
            userunlock
			;;
		17)
		    clear
		    loglimit
			;;
		18)
		    clear
            logban
			;;
	    19)
	        clear
            useraddpptp
			;;
		20)
		    clear
            userdeletepptp
			;;
	    21)
	        clear
            detailpptp
            ;;
        22)
            clear
            userloginpptp
			;;
		23)
		    clear
            alluserpptp
			;;
	    24)
	         clear
             autoreboot
            ;;
	    25)
	         clear
	         #!/bin/bash
            red='\e[1;31m'
            green='\e[0;32m'
            blue='\e[1;34m'
            NC='\e[0m'
            echo "Connecting to autoscriptnobita.tk..."
            sleep 0
			echo "Connecting to your ip : $myip ...."
            sleep 0
            echo "Checking Permision..."
            sleep 0
            echo -e "${green}Permission Accepted...${NC}"
            sleep 0
            echo""
            echo "Speed Test Server"
            ./speedtest.py --share
            echo "Hasil Speed test diatas Script by autoscriptnobita.tk"
            ;;
        26)
            free -m
            ;;
		27)	
		    clear
            echo "Masukan Port OpenVPN yang diinginkan:"
            read -p "Port: " -e -i 1194 PORT
            sed -i "s/port [0-9]*/port $PORT/" /etc/openvpn/1194.conf
            service openvpn restart
            echo "OpenVPN Updated : Port $PORT"
			;;
		28)	
		    clear
            echo "Masukan Port Dropbear yang diinginkan:"
            read -p "Port: " -e -i 443 PORT
            sed -i "s/DROPBEAR_PORT=[0-9]*/DROPBEAR_PORT=$PORT/" /etc/default/dropbear
            service dropbear restart
            echo "Dropbear Updated : Port $PORT"
			;;
        29)	
            clear
            echo "Masukan Port Squid yang diinginkan:"
            read -p "Port: " -e -i 8080 PORT
            sed -i "s/http_port [0-9]*/http_port $PORT/" /etc/squid3/squid.conf
            service squid3 restart
            echo "echo "Squid3 Updated : Port $PORT""
			;;			
        30)	
            clear
            echo ""
            service openvpn restart
            echo ""
			;;	
		31)
            clear
          
            service dropbear restart
           
            ;;
		32) 
		    clear
		    
			service squid3 restart
			
			;;
		33)
		    clear
		    /etc/init.d/webmin restart
		    
		    ;;
		34)
		    clear
            wget freevps.us/downloads/bench.sh -O - -o /dev/null|bash
           ;;
        35)
		    echo "Masukan Password VPS, yang mau diganti :"
		    passwd
			;;	
		36)
			echo "Masukan HOSTNAME VPS, yang mau diganti :"
            echo "  contoh : " hostname autoscriptnobita
            ;;
		37)
		    clear
			reboot
            ;;
        38)
           wget
			;;
        x)
            ;;
        *) menu;;
    esac
